name: first-exercise-workflow
on: [push, pull_request]

jobs:
  shell-cmd-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check Python version
        run: python --version
      - name: Check pip version 
        run: pip --version